name: Ripple Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Create .env.local file
        run: echo "${{ secrets.ENV }}" > .env

      - name: Install dependencies and build
        run: |
          
          npm install --force
          npm run build

      - name: Archive frontend files
        run: |
          tar --ignore-failed-read -czf ripple.tar.gz \
            --exclude="./.git" \
            --exclude="./.git/**" \
            --exclude="./node_modules" \
            --exclude="./node_modules/**" \
            --exclude="./src" \
            --exclude="./src/**" \
            --exclude="./.github" \
            --exclude="./.github/**" \
            .

      - name: Upload files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{secrets.SSH_KEY}}
          port: 21098
          source: "ripple.tar.gz"
          target: "public_html/ripple"

      - name: Extract files on remote server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{secrets.SSH_KEY}}
          port: 21098
          script: |
            cd public_html/ripple
            tar -xzf ripple.tar.gz
            rm ripple.tar.gz

      - name: Restart server process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          key: ${{secrets.SSH_KEY}}
          port: 21098
          script: |
            cd public_html/ripple
            source /home/rippchbn/nodevenv/public_html/ripple/22/bin/activate && cd /home/rippchbn/public_html/ripple && npm install --force
            touch tmp/restart.txt
            